permalink:   none
lsi:         false
#highlighter: pygments
#markdown:    rdiscount
highlighter: rouge
markdown:    kramdown
kramdown:
  input: GFM
  extensions:
    - autolink
    - footnotes
    - smart
#rdiscount:   { extensions: [smart] }
exclude:
  - Gemfile
  - Gemfile.lock
  - script
  - README.markdown

title: "Why's (Poignant) Guide to Ruby"
